# Generated by Django 5.1.5 on 2025-01-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_professores', '0002_professor_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='last_name',
        ),
    ]
